<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Creida</RootNamespace>
    <AssemblyName>Creida</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.*" />
    <PackageReference Include="Markdig" Version="0.*" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\**\*.*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Data\Content\**\*.*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
